from art import *
print('{}'*28)
tprint('DK OFF')

print('''
\033[1;36mESTE SCRIPT TEM COMO FUNCAO RESOLVER CALCULOS.
COMO CALCULOS DE FISICA E MATEMATICA BASICA
SENDO TODOS OS VALORES POSTO CORRETAMENTE SEM FALHA
COM VARIAS OPCOES DE CALCULO

TABEM NO SCRIPT TEMOS A OPCAO DE REALIZAR PESQUISAS
DIRERO DO WIKIPEDIA DO GOOGLE

SE CASO ALGO APRESENTA ERRO INFORME O CRIADOR DO SCRIPT
DONO DO CANAL DK SECURITY TAMBEM CONHECIDO COMO DARK SYSTEM

APROVEITE O SCRIPT PARA FACILITAR QUESTOES DO DIA A DIA

CASO VOCE TENHA ALGUMA SUGESTAO DE MELHORA NOS INFORME TAMBEM

MEU USER DO TELEGRAN ( https://t.me/DkSecurity10 )
\033[m''')
print('{}'*28)